version: "3.8"

services:
  portfolio:
    image: ghcr.io/digital39999/portfolio:latest
    container_name: portfolio
    network_mode: bridge
    pull_policy: build
    restart: always
    ports:
      - ${DOCKER_PORT:-${PORT}}:${PORT}
    env_file:
      - stack.env