export const keywords = [
	'full-stack developer',
	'software engineering',
	'web development',
	'frontend development',
	'backend development',
	'scalable applications',
	'efficient code',
	'programming languages',
	'JavaScript',
	'Python',
	'Java',
	'C#',
	'React',
	'Node.js',
	'Express.js',
	'API development',
	'database management',
	'MySQL',
	'MongoDB',
	'PostgreSQL',
	'SQL',
	'NoSQL',
	'version control',
	'Git',
	'GitHub',
	'deployment',
	'cloud computing',
	'Google Cloud',
	'Docker',
	'microservices',
	'agile development',
	'scrum methodology',
	'continuous integration',
	'unit testing',
	'responsive design',
	'user experience',
	'user interface',
	'UX/UI design',
	'web accessibility',
	'performance optimization',
	'security best practices',
	'cross-browser compatibility',
	'mobile-first design',
	'single-page applications',
	'RESTful services',
	'GraphQL',
	'analytics integration',
	'content management systems',
	'website maintenance',
	'technology trends',
	'developer tools',
	'code quality',
	'software architecture',
	'problem-solving',
	'collaboration',
	'continuous learning',
	'innovation',
];

